language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r server/requirements.txt
script:
  - python -m unittest server
notifications:
  email:
    - alan.le.mouroux@gmail.com
